[32mINFO[0m:     2024-12-09 18:28:03 | Will watch for changes in these directories: ['/home/indianajones/Documents/bangkit/tes-workflow/ml-service']
[32mINFO[0m:     2024-12-09 18:28:03 | Uvicorn running on [1mhttp://127.0.0.1:8000[0m (Press CTRL+C to quit)
[32mINFO[0m:     2024-12-09 18:28:03 | Started reloader process [[36m[1m118067[0m] using [36m[1mwatchgod[0m
[32mINFO[0m:     2024-12-09 18:28:16 | Started server process [[36m118205[0m]
[32mINFO[0m:     2024-12-09 18:28:16 | Waiting for application startup.
[31mERROR[0m:    2024-12-09 18:28:16 | Error loading model: No file or directory found at mood_classifier_bert.keras
Traceback (most recent call last):
  File "/home/indianajones/Documents/bangkit/tes-workflow/ml-service/app/core/models.py", line 14, in load_model
    model = tf.keras.models.load_model(
  File "/home/indianajones/.local/lib/python3.10/site-packages/tf_keras/src/saving/saving_api.py", line 262, in load_model
    return legacy_sm_saving_lib.load_model(
  File "/home/indianajones/.local/lib/python3.10/site-packages/tf_keras/src/utils/traceback_utils.py", line 70, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "/home/indianajones/.local/lib/python3.10/site-packages/tf_keras/src/saving/legacy/save.py", line 233, in load_model
    raise IOError(
OSError: No file or directory found at mood_classifier_bert.keras
[32mINFO[0m:     2024-12-09 18:28:16 | Application startup complete.
[32mINFO[0m:     2024-12-09 18:28:19 | Shutting down
[32mINFO[0m:     2024-12-09 18:28:19 | Finished server process [[36m118205[0m]
[31mERROR[0m:    2024-12-09 18:28:19 | Traceback (most recent call last):
  File "/home/indianajones/.local/lib/python3.10/site-packages/starlette/routing.py", line 700, in lifespan
    await receive()
  File "/usr/lib/python3/dist-packages/uvicorn/lifespan/on.py", line 135, in receive
    return await self.receive_queue.get()
  File "/usr/lib/python3.10/asyncio/queues.py", line 159, in get
    await getter
asyncio.exceptions.CancelledError

[32mINFO[0m:     2024-12-09 18:28:19 | Stopping reloader process [[36m[1m118067[0m]
[32mINFO[0m:     2024-12-09 18:29:29 | Will watch for changes in these directories: ['/home/indianajones/Documents/bangkit/tes-workflow/ml-service']
[32mINFO[0m:     2024-12-09 18:29:29 | Uvicorn running on [1mhttp://127.0.0.1:8000[0m (Press CTRL+C to quit)
[32mINFO[0m:     2024-12-09 18:29:29 | Started reloader process [[36m[1m119428[0m] using [36m[1mwatchgod[0m
[32mINFO[0m:     2024-12-09 18:29:38 | Started server process [[36m119506[0m]
[32mINFO[0m:     2024-12-09 18:29:38 | Waiting for application startup.
[31mERROR[0m:    2024-12-09 18:29:38 | Error loading model: stat: path should be string, bytes, os.PathLike or integer, not NoneType
Traceback (most recent call last):
  File "/home/indianajones/Documents/bangkit/tes-workflow/ml-service/app/core/models.py", line 12, in load_model
    model = tf.keras.models.load_model(MODEL_URL)
  File "/home/indianajones/.local/lib/python3.10/site-packages/keras/src/saving/saving_api.py", line 164, in load_model
    is_keras_dir = file_utils.isdir(filepath) and file_utils.exists(
  File "/home/indianajones/.local/lib/python3.10/site-packages/keras/src/utils/file_utils.py", line 471, in isdir
    return os.path.isdir(path)
  File "/usr/lib/python3.10/genericpath.py", line 42, in isdir
    st = os.stat(s)
TypeError: stat: path should be string, bytes, os.PathLike or integer, not NoneType
[32mINFO[0m:     2024-12-09 18:29:38 | Application startup complete.
[32mINFO[0m:     2024-12-09 18:29:41 | Shutting down
[32mINFO[0m:     2024-12-09 18:29:41 | Finished server process [[36m119506[0m]
[31mERROR[0m:    2024-12-09 18:29:41 | Traceback (most recent call last):
  File "/home/indianajones/.local/lib/python3.10/site-packages/starlette/routing.py", line 700, in lifespan
    await receive()
  File "/usr/lib/python3/dist-packages/uvicorn/lifespan/on.py", line 135, in receive
    return await self.receive_queue.get()
  File "/usr/lib/python3.10/asyncio/queues.py", line 159, in get
    await getter
asyncio.exceptions.CancelledError

[32mINFO[0m:     2024-12-09 18:29:43 | Stopping reloader process [[36m[1m119428[0m]
[32mINFO[0m:     2024-12-09 18:29:50 | Will watch for changes in these directories: ['/home/indianajones/Documents/bangkit/tes-workflow/ml-service']
[32mINFO[0m:     2024-12-09 18:29:50 | Uvicorn running on [1mhttp://127.0.0.1:8000[0m (Press CTRL+C to quit)
[32mINFO[0m:     2024-12-09 18:29:50 | Started reloader process [[36m[1m119700[0m] using [36m[1mwatchgod[0m
[32mINFO[0m:     2024-12-09 18:29:54 | Started server process [[36m119762[0m]
[32mINFO[0m:     2024-12-09 18:29:54 | Waiting for application startup.
[31mERROR[0m:    2024-12-09 18:29:54 | Error loading model: stat: path should be string, bytes, os.PathLike or integer, not NoneType
Traceback (most recent call last):
  File "/home/indianajones/Documents/bangkit/tes-workflow/ml-service/app/core/models.py", line 12, in load_model
    model = tf.keras.models.load_model(MODEL_URL)
  File "/home/indianajones/.local/lib/python3.10/site-packages/keras/src/saving/saving_api.py", line 164, in load_model
    is_keras_dir = file_utils.isdir(filepath) and file_utils.exists(
  File "/home/indianajones/.local/lib/python3.10/site-packages/keras/src/utils/file_utils.py", line 471, in isdir
    return os.path.isdir(path)
  File "/usr/lib/python3.10/genericpath.py", line 42, in isdir
    st = os.stat(s)
TypeError: stat: path should be string, bytes, os.PathLike or integer, not NoneType
[32mINFO[0m:     2024-12-09 18:29:54 | Application startup complete.
[32mINFO[0m:     2024-12-09 18:30:00 | Shutting down
[32mINFO[0m:     2024-12-09 18:30:00 | Finished server process [[36m119762[0m]
[31mERROR[0m:    2024-12-09 18:30:00 | Traceback (most recent call last):
  File "/home/indianajones/.local/lib/python3.10/site-packages/starlette/routing.py", line 700, in lifespan
    await receive()
  File "/usr/lib/python3/dist-packages/uvicorn/lifespan/on.py", line 135, in receive
    return await self.receive_queue.get()
  File "/usr/lib/python3.10/asyncio/queues.py", line 159, in get
    await getter
asyncio.exceptions.CancelledError

[32mINFO[0m:     2024-12-09 18:30:00 | Stopping reloader process [[36m[1m119700[0m]
[32mINFO[0m:     2024-12-09 18:30:33 | Will watch for changes in these directories: ['/home/indianajones/Documents/bangkit/tes-workflow/ml-service']
[32mINFO[0m:     2024-12-09 18:30:33 | Uvicorn running on [1mhttp://127.0.0.1:8000[0m (Press CTRL+C to quit)
[32mINFO[0m:     2024-12-09 18:30:33 | Started reloader process [[36m[1m120232[0m] using [36m[1mwatchgod[0m
[32mINFO[0m:     2024-12-09 18:30:40 | Started server process [[36m120296[0m]
[32mINFO[0m:     2024-12-09 18:30:40 | Waiting for application startup.
[32mINFO[0m:     2024-12-09 18:30:40 | Load Model
[36mDEBUG[0m:    2024-12-09 18:30:40 | Load model from None...
[31mERROR[0m:    2024-12-09 18:30:40 | Error loading model: stat: path should be string, bytes, os.PathLike or integer, not NoneType
Traceback (most recent call last):
  File "/home/indianajones/Documents/bangkit/tes-workflow/ml-service/app/core/models.py", line 12, in load_model
    model = tf.keras.models.load_model(MODEL_URL)
  File "/home/indianajones/.local/lib/python3.10/site-packages/keras/src/saving/saving_api.py", line 164, in load_model
    is_keras_dir = file_utils.isdir(filepath) and file_utils.exists(
  File "/home/indianajones/.local/lib/python3.10/site-packages/keras/src/utils/file_utils.py", line 471, in isdir
    return os.path.isdir(path)
  File "/usr/lib/python3.10/genericpath.py", line 42, in isdir
    st = os.stat(s)
TypeError: stat: path should be string, bytes, os.PathLike or integer, not NoneType
[32mINFO[0m:     2024-12-09 18:30:40 | Model stored in app state
[32mINFO[0m:     2024-12-09 18:30:40 | Application startup complete.
[32mINFO[0m:     2024-12-09 18:31:23 | Shutting down
[32mINFO[0m:     2024-12-09 18:31:23 | Finished server process [[36m120296[0m]
[31mERROR[0m:    2024-12-09 18:31:23 | Traceback (most recent call last):
  File "/home/indianajones/.local/lib/python3.10/site-packages/starlette/routing.py", line 700, in lifespan
    await receive()
  File "/usr/lib/python3/dist-packages/uvicorn/lifespan/on.py", line 135, in receive
    return await self.receive_queue.get()
  File "/usr/lib/python3.10/asyncio/queues.py", line 159, in get
    await getter
asyncio.exceptions.CancelledError

[32mINFO[0m:     2024-12-09 18:31:23 | Stopping reloader process [[36m[1m120232[0m]
[32mINFO[0m:     2024-12-09 18:31:29 | Will watch for changes in these directories: ['/home/indianajones/Documents/bangkit/tes-workflow/ml-service']
[32mINFO[0m:     2024-12-09 18:31:29 | Uvicorn running on [1mhttp://127.0.0.1:8000[0m (Press CTRL+C to quit)
[32mINFO[0m:     2024-12-09 18:31:29 | Started reloader process [[36m[1m120864[0m] using [36m[1mwatchgod[0m
[32mINFO[0m:     2024-12-09 18:31:33 | Started server process [[36m120933[0m]
[32mINFO[0m:     2024-12-09 18:31:33 | Waiting for application startup.
[32mINFO[0m:     2024-12-09 18:31:33 | Load Model
[36mDEBUG[0m:    2024-12-09 18:31:33 | Load model from None...
[31mERROR[0m:    2024-12-09 18:31:33 | Error loading model: stat: path should be string, bytes, os.PathLike or integer, not NoneType
Traceback (most recent call last):
  File "/home/indianajones/Documents/bangkit/tes-workflow/ml-service/app/core/models.py", line 12, in load_model
    model = tf.keras.models.load_model(MODEL_URL)
  File "/home/indianajones/.local/lib/python3.10/site-packages/keras/src/saving/saving_api.py", line 164, in load_model
    is_keras_dir = file_utils.isdir(filepath) and file_utils.exists(
  File "/home/indianajones/.local/lib/python3.10/site-packages/keras/src/utils/file_utils.py", line 471, in isdir
    return os.path.isdir(path)
  File "/usr/lib/python3.10/genericpath.py", line 42, in isdir
    st = os.stat(s)
TypeError: stat: path should be string, bytes, os.PathLike or integer, not NoneType
[32mINFO[0m:     2024-12-09 18:31:33 | Model stored in app state
[32mINFO[0m:     2024-12-09 18:31:33 | Application startup complete.
[32mINFO[0m:     2024-12-09 18:32:02 | Shutting down
[32mINFO[0m:     2024-12-09 18:32:02 | Finished server process [[36m120933[0m]
[31mERROR[0m:    2024-12-09 18:32:02 | Traceback (most recent call last):
  File "/home/indianajones/.local/lib/python3.10/site-packages/starlette/routing.py", line 700, in lifespan
    await receive()
  File "/usr/lib/python3/dist-packages/uvicorn/lifespan/on.py", line 135, in receive
    return await self.receive_queue.get()
  File "/usr/lib/python3.10/asyncio/queues.py", line 159, in get
    await getter
asyncio.exceptions.CancelledError

[32mINFO[0m:     2024-12-09 18:32:02 | Stopping reloader process [[36m[1m120864[0m]
[32mINFO[0m:     2024-12-09 18:32:31 | Will watch for changes in these directories: ['/home/indianajones/Documents/bangkit/tes-workflow/ml-service']
[32mINFO[0m:     2024-12-09 18:32:31 | Uvicorn running on [1mhttp://127.0.0.1:8000[0m (Press CTRL+C to quit)
[32mINFO[0m:     2024-12-09 18:32:31 | Started reloader process [[36m[1m121616[0m] using [36m[1mwatchgod[0m
[32mINFO[0m:     2024-12-09 18:32:34 | Started server process [[36m121666[0m]
[32mINFO[0m:     2024-12-09 18:32:34 | Waiting for application startup.
[32mINFO[0m:     2024-12-09 18:32:34 | Load Model
[36mDEBUG[0m:    2024-12-09 18:32:34 | Load model from None...
[31mERROR[0m:    2024-12-09 18:32:34 | Error loading model: stat: path should be string, bytes, os.PathLike or integer, not NoneType
Traceback (most recent call last):
  File "/home/indianajones/Documents/bangkit/tes-workflow/ml-service/app/core/models.py", line 12, in load_model
    model = tf.keras.models.load_model(MODEL_URL)
  File "/home/indianajones/.local/lib/python3.10/site-packages/keras/src/saving/saving_api.py", line 164, in load_model
    is_keras_dir = file_utils.isdir(filepath) and file_utils.exists(
  File "/home/indianajones/.local/lib/python3.10/site-packages/keras/src/utils/file_utils.py", line 471, in isdir
    return os.path.isdir(path)
  File "/usr/lib/python3.10/genericpath.py", line 42, in isdir
    st = os.stat(s)
TypeError: stat: path should be string, bytes, os.PathLike or integer, not NoneType
[32mINFO[0m:     2024-12-09 18:32:35 | Model stored in app state
[32mINFO[0m:     2024-12-09 18:32:35 | Application startup complete.
[32mINFO[0m:     2024-12-09 18:32:53 | Shutting down
[32mINFO[0m:     2024-12-09 18:32:53 | Finished server process [[36m121666[0m]
[31mERROR[0m:    2024-12-09 18:32:53 | Traceback (most recent call last):
  File "/home/indianajones/.local/lib/python3.10/site-packages/starlette/routing.py", line 700, in lifespan
    await receive()
  File "/usr/lib/python3/dist-packages/uvicorn/lifespan/on.py", line 135, in receive
    return await self.receive_queue.get()
  File "/usr/lib/python3.10/asyncio/queues.py", line 159, in get
    await getter
asyncio.exceptions.CancelledError

[32mINFO[0m:     2024-12-09 18:32:53 | Stopping reloader process [[36m[1m121616[0m]
[32mINFO[0m:     2024-12-09 18:32:58 | Will watch for changes in these directories: ['/home/indianajones/Documents/bangkit/tes-workflow/ml-service']
[32mINFO[0m:     2024-12-09 18:32:58 | Uvicorn running on [1mhttp://127.0.0.1:8000[0m (Press CTRL+C to quit)
[32mINFO[0m:     2024-12-09 18:32:58 | Started reloader process [[36m[1m121949[0m] using [36m[1mwatchgod[0m
[32mINFO[0m:     2024-12-09 18:33:02 | Started server process [[36m122012[0m]
[32mINFO[0m:     2024-12-09 18:33:02 | Waiting for application startup.
[32mINFO[0m:     2024-12-09 18:33:02 | Load Model
[36mDEBUG[0m:    2024-12-09 18:33:02 | Load model from memotions.keras...
[32mINFO[0m:     2024-12-09 18:33:04 | Model stored in app state
[32mINFO[0m:     2024-12-09 18:33:04 | Application startup complete.
[32mINFO[0m:     2024-12-09 19:14:24 | Shutting down
[32mINFO[0m:     2024-12-09 19:14:24 | Finished server process [[36m122012[0m]
[31mERROR[0m:    2024-12-09 19:14:24 | Traceback (most recent call last):
  File "/home/indianajones/.local/lib/python3.10/site-packages/starlette/routing.py", line 700, in lifespan
    await receive()
  File "/usr/lib/python3/dist-packages/uvicorn/lifespan/on.py", line 135, in receive
    return await self.receive_queue.get()
  File "/usr/lib/python3.10/asyncio/queues.py", line 159, in get
    await getter
asyncio.exceptions.CancelledError

[32mINFO[0m:     2024-12-09 19:14:24 | Stopping reloader process [[36m[1m121949[0m]
